name: (CI) Merge Dev

on:
  push:
    paths:
      - src/**
      - package.json
      - package-lock.json
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/manual-run-test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/manual-build-deploy.yml
    secrets: inherit
    with:
      deploy_nt_dev: true