name: (Manual) Deploy Dev

on:
  # enable call from another workflow
  workflow_call:

  # enable run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run
      run: docker-compose up --build -d
      env:
        ENV_FILE: .env.dev